baseURL = 'https://hogandenver05.github.io/Eato/'
languageCode = 'en-us'
title = 'Eato Meal Tracker - Portfolio'

[params]
  description = 'A RESTful API built with Laravel and MySQL for ASE 230 Project 1 & 2'
  author = 'Denver Hogan'

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'üçé Eato Meal Tracker'
    url = '/'
    weight = 1
  [[menu.main]]
    identifier = 'portfolio'
    name = 'Portfolio'
    url = '/portfolio/'
    weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
